spring:
  application:
    name: order
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

